### PR TITLE
Add CI envs for PyQt 6.5-6.7, PySide 6.5-6.7 & Python 3.12; fix Readthedocs and matplotlib 3.9, Qt6 failures

### PR DESCRIPTION
**Pull request by dhomeier**
## Description
WIP

### CODE REVIEW

**Comment by dhomeier** [comment]
Same #16 failures on `ScatterRegionLayerArtist.enabled`

**Comment by dhomeier** [comment]
@astrofrog it seems I cannot cancel workflows here (might not have the right permissions?), so would rather not experiment more in the CI at this point (haven't tested any py312+PyQT 5 combinations)

**Comment by dhomeier** [comment]
@astrofrog I think #16 may be closed now through glue-viz/glue#2479, but there are 2 new errors probably introduced with glue-viz/glue#2480, e.g. in `_update_attribute_display_unit_choices`:
https://github.com/glue-viz/glue-qt/actions/runs/8758215189/job/24038566338?pr=17#step:10:687
and on calling `Unit(None)` from a session file
https://github.com/glue-viz/glue-qt/actions/runs/8758215189/job/24038566338?pr=17#step:10:430

Also all py312 jobs still hanging in test_data_viewer.

**Comment by astrofrog** [comment]
@dhomeier - could you rebase to pick up the fixes in https://github.com/glue-viz/glue-qt/pull/21? (doesn't fix everything but at least a few jobs)

**Comment by dhomeier** [comment]
> @dhomeier - could you rebase to pick up the fixes in #21? (doesn't fix everything but at least a few jobs)

I haven't followed the CI updates closely – has the default macOS-latest runner changed to arm64 since? Don't recall that many segfaults from before anyway, but the newer PyQt6 versions seem to be more stable. Same 4-6 failures though.

**Comment by dhomeier** [comment]
Well ,the first common failure rather seems to be a matplotlib thing, but I am struggling to see how this could ever have worked even with mpl 3.5
https://github.com/glue-viz/glue-qt/actions/runs/9940878742/job/27458723480#step:10:283
– `set_xy` interface has not changed there, would this mean it has not been using a `Rectangle` in the older setups??

**Comment by dhomeier** [comment]
I think it might indeed be `axvspan` changed from using `Polygon` to `Rectangle` in matplotlib/matplotlib#26788!

**Comment by dhomeier** [comment]
@astrofrog the two remaining failures are now worked around in a rather hackish manner, that's as much as I could come up with (I tried with a wait in `process_events()`, but to no avail).
The macOS 14-PyQt5 test could perhaps be saved by skipping `TestGlueDataDialog` and `TestLinkEditor` tests, but that would require a bunch of system-version and architecture conditionals.
Re-enabled a test that was probably mistakenly skipped on Qt6; perhaps `requires_pyqt_gt_59_or_pyside2` should be updated upstream, or maybe the Qt test helpers should actually be moved into this repo?
PySide6 is now at 6.7.2; haven't looked closely at those failures.

**Comment by astrofrog** [comment]
@dhomeier - regarding the Qt test helpers, yes they should be moved to this repo, would you be able to do that here?

I think the hackish fixes will have to do for now!

**Comment by astrofrog** [comment]
Can you rebase to take into account https://github.com/glue-viz/glue-qt/pull/12, as this might fix some of the issues?

**Comment by dhomeier** [comment]
@astrofrog adding a `wait` to `process_events()` seemed to resolve _one_ test, but I am leaving the hacks for the remaining ones.

The QT_anything helpers could be removed from glue core at some point. Maybe `make_marker` should also be completely defined here, so the glue-core version would not need the extra PyQt5/6 foo?

**Pull request merged**
